### ISSUE TITLE
Signalstärke

### ISSUE THREAD

**Issue by OverSave** [frankjoke/ioBroker.radar2#10]
Bei den Unbekannten Bluetoothgeräten sieht man die rssi, ist es auch bei den Bekannten möglich?

**Comment by frankjoke** [comment]
Bei BT LE wird die Information geliefert aber nicht verwendet. Ich glaub vielleicht mit dem BLE-Adapter, aber der kann nur auf einem anderen stick gleichzeitig mit radar laufen.
