### ISSUE TITLE
Adapter finds the hosts on the local network only with addresses obtained from dhcp

### ISSUE THREAD

**Issue by electric69** [frankjoke/ioBroker.radar2#11]
in my local network there are automation devices (PLC) with static ip, the driver did not find them when scanning. but the command `arp-scan -lgq --retry = 5 --timeout = 400` displays all active hosts on the network, including those with a static ip address
Armbian on Cubietruck

**Comment by frankjoke** [comment]
I do not know what you mean with find. It does not search for devices which you don't configure but if it sees some it flags them as unknown.
