### ISSUE TITLE
Extreme CPU Auslastung bei Bluetooth nutzung

### ISSUE THREAD

**Issue by haahne** [frankjoke/ioBroker.radar2#115]
Hallo, 
ich nutze Iobroker mit 4 Cores unter Proxmox und habe immer um die 9-10 Prozent Auslastung.
Ich hab im Adapter 2 Bluetooth Geräte und 2 Normale angegeben. Mit den 2 Bluetooth Geräten steigt die IObroker Last unter Proxmox auf um die 30% ist das normal? Nehme ich die Bluetooth Geräte raus ist alles wieder normal.
Grüße

**Comment by Apollon77** [comment]
WHich version? ANd yes reason most likely known ... update (downgrade of noble) will come soon

**Comment by Apollon77** [comment]
radar2 2.0.5 on it's way
