### ISSUE TITLE
_lastHere wird aktualisiert obwohl der Adapter deaktiviert ist

### ISSUE THREAD

**Issue by roe19xx** [frankjoke/ioBroker.radar2#13]
Ich habe schon länger Radar1 im Einsatz und habe nun vor zwei Tagen (07.05.2019) eine Radar2 Instanz installiert.

Die Radar2 Instanz habe ich dann am 07.05.2019 wieder vorübergehend deaktiviert.

Heute ist mir aber aufgefallsen das bei allen Bluetooth Geräten der "_lastHere" Zeitstempel, trotz deaktiviertem Adapter aktualisiert wird.

Wenn ich mir den Zeitstempel vom "_here" Wert anschaue, dann passt dieser. Der wurde am 07.05.2019 zum letzten mal aktualisiert.

Auch die "unkown BT's" werden scheinbar bei deaktiviertem Adapter akualisiert.

Interessanterweise werden die Datenpunkte "_lastHere" bei den IP Adressen nicht aktulisiert.

Ich hatte den Radar2 Adapter zuerst auf dem falschen ioBroker Host laufen und habe im Admin Adapter dann den Host für die Radar2 Instanz umgeschalten.
Ggf. ist auch dort etwas schief gegangen?

Habe den Radar2 Adapter voerst mal deaktiviert und wollte hier einfach mal Feedback geben. Falls ich etwas testen soll, dann gerne.

**Comment by frankjoke** [comment]
Deine Schilderung deutet darauf hin dass der Adapter (oder besser gesagt die BT-Erkennung) wegen noble im Hintergrund weiter läuft.

starte mal `sudo pkill -f io.radar2.0` um alle Tasks im Hintergrund zu schließen, vielleicht mit `top` nachschauen.

Noble kann manchmal leider nicht geschlossen werden und dann hängt der Adapter im Hintergrund obwohl ioBroker ihn geschlossen hat.

Kannst ja mal mit HCIonly probieren...
