### ISSUE TITLE
arp-scan interface Parameter wird ignoriert und Fehlerhandling unvollständig

### ISSUE THREAD

**Issue by mesche** [frankjoke/ioBroker.radar2#14]
Hallo,

wird in der Konfiguration für die `arp-scan` Kommandozeile der Parameter "--interface" angegeben, wird dieser trotzdem ignoriert, weil die if-Bedingung fehlerhaft ist.

https://github.com/frankjoke/ioBroker.radar2/blob/1091ee10d283e6eebf5a65822295616675e9e9ca/myNetworks.js#L1051

Korrekt wäre:
``
if (!args.indexOf('--interface='))
``
oder besser
``
if (args.indexOf('--interface=') !== -1 || args.indexOf(' -I') !== -1)
``

Zusätzlich sollte das Fehlerhandling bzw. die Fehlerausgabe verbessert werden. 
Gibt `arp-scan` kein Result zurück, wird einfach folgende Meldung ausgegeben `arp-scan maybe without rights because no data returned!`
Es muss aber nicht immer an den Berechtigungen liegen und somit bleibt der eigentliche Fehler unklar für den Benutzer.

Gruß
Esche

**Comment by frankjoke** [comment]
Habe die if-Abfrage geändert (ohne Leerzeichen vor dem -I) 
Die Fehlermeldung nicht da ich annehme dass jeder der die Kommandozeile ändert dies mal selbst testet und die Fehler dann vorher sieht, die meldet arp-scan ja auf dem Fehler-stream und stdout bleibt leer.

**Comment by mesche** [comment]
Das Leerzeichen war nur zur Sicherheit, dass es keine Verwechslung mit anderen Parametern gibt. Da diese aber Case-Sensitive sind, sollte dies eh nicht passieren.

Nochmal kurz zur Fehlermeldung:
Der Hintergrund meiner Anmerkung war folgender:
Wenn ich keinen Interface-Parameter explizit angebe, dann findet er meine 3 Interfaces [ 'eth0', 'eth0:0', 'tun0' ] und versucht jeweils den `arp-scan` Befehl aufzurufen.

Hier bekomme ich dann aber die Fehlermeldung: 

> 'arp-scan maybe without rights because no data returned!'

Dies hat mich am Anfang sehr verwirrt, bis ich den eigentlichen Fehler gefunden hatte. Wenn ich arp-scan direkt in der der Konsole ausführe, bekomme ich nämlich ganz andere Fehlermeldungen:

> ERROR: Check that the interface exists and is up
> ERROR: Could not obtain MAC address for interface tun0

Gruß
Esche
