### ISSUE TITLE
_here wird nicht auf false gesetzt, obwohl Device seit Stunden nicht mehr da ist

### ISSUE THREAD

**Issue by MarkSau** [frankjoke/ioBroker.radar2#16]
Ich habe da ein Device, welches laut _Lasthere seit 6:20 nicht mehr da ist, wird unter _Here immer noch (Stand 10:50) mit TRUE, also anwesend, gekennzeichnet. Auch ein Neustart des Adapters ändert daran nichts...

Radar2: 1.2.0
node: v10.15.3
npm: 6.9.0

**Comment by MarkSau** [comment]
Habe den IOB Server jetzt mal gebootet...Danach war der Status richtig gesetzt. Meiner Meinung nach sollte das aber auch ohne Reboot funktionieren..

**Comment by frankjoke** [comment]
Ich stimme dir zui, kann aber ohne debug logs nicht sehen was da schief geht!
