### ISSUE TITLE
radar2.0._nHere not set to zero

### ISSUE THREAD

**Issue by MarkSau** [frankjoke/ioBroker.radar2#3]
At first, great job. I think the new adapter is very well done.
But...After all clients are gone the field radar2.0._nHere will not set to zero. 
radar2.0._isHere is empty.
I'm online:
![image](https://user-images.githubusercontent.com/22911084/54415626-1d138700-46fd-11e9-9ba2-dd889dc5d7ee.png)
Now away:
![image](https://user-images.githubusercontent.com/22911084/54415637-256bc200-46fd-11e9-8661-ab7e52b4061e.png)
Please check and fix.
installed version is 1.0.1

**Comment by frankjoke** [comment]
Fehler auch gefunden, ein string mit split und join bearbeitet bleibt leider immer ein Array mit >0 Werten!
