### ISSUE TITLE
Erstes Erkennen einen Objektes funktioniert nicht

### ISSUE THREAD

**Issue by MarkSau** [frankjoke/ioBroker.radar2#4]
Ich habe div. Geräte in der Objekt Liste eingetragen, bevor diese sich im Netz angemeldet haben.
Nun kommt das Gerät online, Radar2 erkennt es jedoch nicht. 
![image](https://user-images.githubusercontent.com/22911084/54529996-cb2f6300-4981-11e9-8ec7-ad558345821a.png)
![image](https://user-images.githubusercontent.com/22911084/54530037-ec904f00-4981-11e9-8182-4e847bfa094d.png)
![image](https://user-images.githubusercontent.com/22911084/54530070-0762c380-4982-11e9-9e01-34bb286aa88f.png)
![image](https://user-images.githubusercontent.com/22911084/54530175-60caf280-4982-11e9-85f7-808c8eed20e1.png)

UPDATE: Nach Restart des Radar2 Adapters funktioniert es..Die Folge ist dann aber, das ich für jedes neue Objekt, den Adapter neu starten muss.

**Comment by frankjoke** [comment]
Sollte jetzt behoben sein, trat bei mir nur auf wenn klein hostname und kein ip sondern nur ein mac angegeben wurde.
