### ISSUE TITLE
BT not working

### ISSUE THREAD

**Issue by daniel-lo** [frankjoke/ioBroker.radar2#46]
Hi .. could anyone help me with this?

radar2.0 | 2020-04-28 11:02:58.936 | info | (928) radar2 set to scan every 20 seconds and printers every 720 minutes.
-- | -- | -- | --
radar2.0 | 2020-04-28 11:02:58.935 | info | (928) arp-scan will use the following interfaces: [ 'ens18' ]
radar2.0 | 2020-04-28 11:02:58.935 | info | (928) Remove name end for host names: .fritz.box
radar2.0 | 2020-04-28 11:02:58.934 | info | (928) use known IP list: []
radar2.0 | 2020-04-28 11:02:58.934 | info | (928) use known BT list: []
radar2.0 | 2020-04-28 11:02:58.934 | info | (928) radar2 set to flag items away if they are not seen for 2 minutes
radar2.0 | 2020-04-28 11:02:58.933 | warn | (928) node-bluetooth not found!
radar2.0 | 2020-04-28 11:02:58.932 | warn | (928)  Noble not available, Error: Error: The module  '/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/binding.node'was  compiled against a different Node.js version usingNODE_MO
radar2.0 | 2020-04-28 11:02:58.852 | info | (928) Adapter disconnected and stopped with dostop(false) and callback(true)
radar2.0 | 2020-04-28 11:02:58.851 | error | (928) Error: bind EACCES 0.0.0.0:67     at dgram.js:339:20     at processTicksAndRejections (internal/process/task_queues.js:85:21)
radar2.0 | 2020-04-28 11:02:58.851 | error | (928) uncaught exception: bind EACCES 0.0.0.0:67
radar2.0 | 2020-04-28 11:02:58.778 | info | (928) net-ping not available! Will try to use normal ping!
radar2.0 | 2020-04-28 11:02:58.773 | info | (928) radar2 initialization started...
radar2.0 | 2020-04-28 11:02:58.764 | warn | (928)  adapter.objects.getObjectList is deprecated, and will be removed in the  future. Please use adapter.getObjectList/Async. Report this to  Developer!
radar2.0 | 2020-04-28 11:02:58.713 | info | (928) starting. Version 1.0.9 in /opt/iobroker/node_modules/iobroker.radar2, node: v12.16.2, js-controller: 3.0.19
radar2.0 | 2020-04-28 09:02:27.327 | info | (32526) radar2 set to scan every 20 seconds and printers every 720 minutes.
radar2.0 | 2020-04-28 09:02:27.327 | info | (32526) arp-scan will use the following interfaces: [ 'ens18' ]
radar2.0 | 2020-04-28 09:02:27.326 | info | (32526) Remove name end for host names: .fritz.box
radar2.0 | 2020-04-28 09:02:27.326 | info | (32526) use known IP list: []
radar2.0 | 2020-04-28 09:02:27.325 | info | (32526) use known BT list: []
radar2.0 | 2020-04-28 09:02:27.325 | info | (32526) radar2 set to flag items away if they are not seen for 2 minutes
radar2.0 | 2020-04-28 09:02:27.325 | warn | (32526) node-bluetooth not found!
radar2.0 | 2020-04-28 09:02:27.323 | warn | (32526) Noble not available, Error: Error: The module  '/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/binding.node'was  compiled against a different Node.js version usingNODE
radar2.0 | 2020-04-28 09:02:27.170 | info | (32526) Adapter disconnected and stopped with dostop(false) and callback(true)
radar2.0 | 2020-04-28 09:02:27.169 | error | at processTicksAndRejections (internal/process/task_queues.js:85:21)
radar2.0 | 2020-04-28 09:02:27.169 | error | at dgram.js:339:20
radar2.0 | 2020-04-28 09:02:27.169 | error | (32526) Error: bind EACCES 0.0.0.0:67
radar2.0 | 2020-04-28 09:02:27.168 | error | (32526) uncaught exception: bind EACCES 0.0.0.0:67
radar2.0 | 2020-04-28 09:02:27.093 | info | (32526) net-ping not available! Will try to use normal ping!
radar2.0 | 2020-04-28 09:02:27.084 | info | (32526) radar2 initialization started...
radar2.0 | 2020-04-28 09:02:27.074 | warn | (32526) adapter.objects.getObjectList is deprecated, and will be  removed in the future. Please use adapter.getObjectList/Async. Report  this to Developer!
radar2.0 | 2020-04-28 09:02:27.020 | info | (32526) starting. Version 1.0.9 in /opt/iobroker/node_modules/iobroker.radar2, node: v12.16.2, js-controller: 3.0.19

**Comment by frankjoke** [comment]
You may miss access rights.  are you running on linux and did you run scripts from readme after install?
You need to re-run scripts also after update of nodejs again!

**Comment by daniel-lo** [comment]
just ran through them .. no change

**Comment by daniel-lo** [comment]
Interesting .. I found this screenshot in the forum. Are the settings "hcitool lescan anstelle von Noble verwenden" .. completely gone or hidden?
![radar2config](https://user-images.githubusercontent.com/4311558/80645915-17e1da80-8a6c-11ea-980f-f7180aacd0dc.png)

**Comment by daniel-lo** [comment]
green now:

daniel@iobroker:/opt/iobroker$ node -v
v10.20.1
daniel@iobroker:/opt/iobroker$ nodejs -v
v10.20.1
daniel@iobroker:/opt/iobroker$ npm -v
6.14.4

In fact there seems to be an problem with newer versions of node/nodejs.

**Comment by daniel-lo** [comment]
found this fyi:

radar2.0 | 2020-04-30 06:02:15.384 | warn | (17084) Promise failed @ '_tickCallback in  internal/process/next_tick.js @68:7' error: { SyntaxError: Unexpected  token c in JSON at position 0 at JSON.parse (<anonymous>) at  A.get.then.res (/opt/iobr
-- | -- | -- | --
radar2.0 | 2020-04-30 06:02:14.472 | warn | (17084) adapter.objects.getObjectList is deprecated, and will be  removed in the future. Please use adapter.getObjectList/Async. Report  this to Developer!

**Comment by frankjoke** [comment]
I am not sure which devices you screen but the first entry is because one of the devices return no or an invalid response. The second one is because you use latest js-controller but not latest (from git) radar2.

**Comment by daniel-lo** [comment]
actually I just spent time getting this and another adapter up and running .. I didn't really use it .. so all must be default. But I will delete the object tree .. maybe there are some legacy objects from a former try.

**Comment by daniel-lo** [comment]
My output after deleting the objects and restarting the adapter:


radar2.0 | 2020-05-01 06:16:35.387 | info | (32753) radar2 set use of noble(true), doArp("-lgq --retry=5  --timeout=400" on ens18), btid(0) and doUwz(UWZDE14612,120,0,de,true).
-- | -- | -- | --
radar2.0 | 2020-05-01 06:16:35.387 | info | (32753) radar2 found 6 devices in config (Ich-,Fritzbox,G-Tags,HP-7520-,ECB-,Forum)
radar2.0 | 2020-05-01 06:16:35.178 | info | (32753) will scan printers  [ 'HP-7520-' ]  every  720  minutes
radar2.0 | 2020-05-01 06:16:34.851 | info | (32753) UWZ found the following (changed) warnings: Am  Freitagnachmittag und -abend besteht ein leichtes Risiko für teils  kräftige Schauer und örtliche Gewitter, die vereinzelt mit Starkregen um  10 L
radar2.0 | 2020-05-01 06:16:34.751 | info | (32753) Will scan ECB for  [ 'USD,RUB,GBP' ]  every  60  minutes
radar2.0 | 2020-05-01 06:16:34.747 | info | (32753) will scan UWZ with code UWZDE14612 every 120 minutes
radar2.0 | 2020-05-01 06:16:33.873 | warn | (32753) adapter.objects.getObjectList is deprecated, and will be  removed in the future. Please use adapter.getObjectList/Async. Report  this to Developer!
radar2.0 | 2020-05-01 06:16:33.872 | info | bts: (01:23:45:56:78:89:90,01:23:45:56:78:89:99)
radar2.0 | 2020-05-01 06:16:33.872 | info | ips: (127.0.0.1,::1,192.168.178.1),
radar2.0 | 2020-05-01 06:16:33.872 | info | (32753) Adapter identified macs: (12:34:56:78:90:12,44:4e:6d:29:c9:a8),
radar2.0 | 2020-05-01 06:16:33.853 | info | (32753) New external IP address 91.65.84.196
radar2.0 | 2020-05-01 06:16:33.671 | info | (32753) Init item Forum with { name: 'Forum',ip:  'https://forum.iobroker.net',id: 'Forum',type: 'URL',lasthere:  '2020-05-01T06:14:33.550Z',anwesend: false }
radar2.0 | 2020-05-01 06:16:33.570 | info | (32753) Init item ECB- with { name: 'ECB-', ip: 'USD,RUB,GBP', id: 'ECB', type: 'ECB' }
radar2.0 | 2020-05-01 06:16:33.543 | info | (32753) Init item HP-7520- with { name: 'HP-7520-',ip: 'HPC56C03-PS7520',id: 'HP-7520',type: 'printer' }
radar2.0 | 2020-05-01 06:16:33.487 | info | (32753) Init item G-Tags with { name: 'G-Tags',bluetooth: [  '01:23:45:56:78:89:90', '01:23:45:56:78:89:99' ],id: 'G-Tags',type:  'BT',btVendor: 'Vendor N/A',lasthere: '2020-05-01T06:14:33.367Z',anwese
radar2.0 | 2020-05-01 06:16:33.419 | info | (32753) Init item Fritzbox with { name: 'Fritzbox',id: 'Fritzbox',type:  'IP',hasMAC: [ '12:34:56:78:90:12', '44:4e:6d:29:c9:a8' ],ipVendor:  'Vendor N/A',rip: [ '192.168.178.1', '192.168.178.1' ],last
radar2.0 | 2020-05-01 06:16:33.321 | warn | (32753) ip address 192.168.178.1 in Fritzbox was used already for another device Fritzbox, this is forbidden!
radar2.0 | 2020-05-01 06:16:33.309 | info | (32753) Init item Ich- with { name: 'Ich-',id: 'Ich',type: 'IP',rip: [  '127.0.0.1', '::1' ],lasthere: '2020-05-01T06:14:33.186Z',anwesend:  false }
radar2.0 | 2020-05-01 06:16:32.793 | info | (32753) Will try to scan BT devices: true
radar2.0 | 2020-05-01 06:16:32.765 | info | (32753) radar2 set to scan every 20 seconds and printers every 720 minutes.
radar2.0 | 2020-05-01 06:16:32.765 | info | (32753) arp-scan will use the following interfaces: [ 'ens18' ]
radar2.0 | 2020-05-01 06:16:32.764 | info | (32753) Remove name end for host names: .fritz.box
radar2.0 | 2020-05-01 06:16:32.764 | info | (32753) use known IP list: [ '1.1.1.1' ]
radar2.0 | 2020-05-01 06:16:32.764 | info | (32753) use known BT list: [ '01:12:23:34:45:56' ]
radar2.0 | 2020-05-01 06:16:32.763 | info | (32753) radar2 set to flag items away if they are not seen for 2 minutes
radar2.0 | 2020-05-01 06:16:32.762 | warn | (32753) node-bluetooth not found!
radar2.0 | 2020-05-01 06:16:32.751 | info | (32753) found '@abandonware/noble'
radar2.0 | 2020-05-01 06:16:32.609 | info | (32753) Connected with '0.0.0.0' for DHCP Scan
radar2.0 | 2020-05-01 06:16:32.532 | info | (32753) net-ping not available! Will try to use normal ping!
radar2.0 | 2020-05-01 06:16:32.519 | info | (32753) radar2 initialization started...
radar2.0 | 2020-05-01 06:16:32.435 | warn | (32753) adapter.objects.getObjectList is deprecated, and will be  removed in the future. Please use adapter.getObjectList/Async. Report  this to Developer!
radar2.0 | 2020-05-01 06:16:32.375 | info | (32753) starting. Version 1.0.9 in /opt/iobroker/node_modules/iobroker.radar2, node: v10.20.1, js-controller: 3.0.20

**Comment by frankjoke** [comment]
Can you load the latest adapter from git and check? The objlist warning shoul be gon, everything else is normal.

**Comment by daniel-lo** [comment]
Yes .. that one is gone. I installed via git and the situation I have now is that the installation worked but I get an adapter update in the adapter list. Installed 1.2.0 Available 1.2.3 .. is there any variable possibly have forgotten to update?

**Comment by Speedbreaker12** [comment]
Same issue here, always shows 1.2.3 is available even though it's already installed.

**Comment by frankjoke** [comment]
Updated to  1.2.5 on git and npm working on my old node v8 controller 2.x and node v12 controller 3.x now, changed also in text.  p.s. if you run it on Windows you cannot use hcitools!

**Comment by daniel-lo** [comment]
don't know whom this Windows comment adresses .. I'm on Ubuntu VM in Proxmox

**Comment by frankjoke** [comment]
But you found an old screenshot on the forum without the hci-tool switch!

**Comment by daniel-lo** [comment]
oh .. yes .. that was not mine :-)
