### ISSUE TITLE
Update not possible

### ISSUE THREAD

**Issue by Voodoo2man** [frankjoke/ioBroker.radar2#47]
Hello,
The upgrade from 1.2.0 to 1.2.3 starts and finishes as expected, but the version is still shown as 1.2.0.
Tried several times. Restartet the Raspi, but still have 1.2.0

> Update radar2 from @1.2.0 to @1.2.3
NPM version: 6.14.4
npm install iobroker.radar2@1.2.3 --loglevel error --prefix "/opt/iobroker" (System call)
In file included from ../src/DeviceINQ.h:17,
                 from ../src/linux/BluetoothSerialPort.cc:13:
../node_modules/nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../node_modules/nan/nan.h:2294:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
../src/linux/BluetoothSerialPort.cc: At global scope:
../src/linux/BluetoothSerialPort.cc:18:14: error: variable or field ‘InitAll’ declared void
 void InitAll(Handle<Object> exports) {
              ^~~~~~
../src/linux/BluetoothSerialPort.cc:18:14: error: ‘Handle’ was not declared in this scope
../src/linux/BluetoothSerialPort.cc:18:14: note: suggested alternative: ‘rand_r’
 void InitAll(Handle<Object> exports) {
              ^~~~~~
              rand_r
../src/linux/BluetoothSerialPort.cc:18:27: error: expected primary-expression before ‘>’ token
 void InitAll(Handle<Object> exports) {
                           ^
../src/linux/BluetoothSerialPort.cc:18:29: error: ‘exports’ was not declared in this scope
 void InitAll(Handle<Object> exports) {
                             ^~~~~~~
In file included from ../src/linux/BluetoothSerialPort.cc:12:
../src/linux/BluetoothSerialPort.cc:23:34: error: ‘InitAll’ was not declared in this scope
 NODE_MODULE(BluetoothSerialPort, InitAll)
                                  ^~~~~~~
/home/iobroker/.cache/node-gyp/12.16.3/include/node/node.h:608:36: note: in definition of macro ‘NODE_MODULE_X’
       (node::addon_register_func) (regfunc),                          \
                                    ^~~~~~~
../src/linux/BluetoothSerialPort.cc:23:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(BluetoothSerialPort, InitAll)
 ^~~~~~~~~~~
make: *** [BluetoothSerialPort.target.mk:115: Release/obj.target/BluetoothSerialPort/src/linux/BluetoothSerialPort.o] Fehler 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.19.97-v7l+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /opt/iobroker/node_modules/node-bluetooth
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
upload [13] radar2.admin /opt/iobroker/node_modules/iobroker.radar2/admin/words.js words.js application/javascript
upload [12] radar2.admin /opt/iobroker/node_modules/iobroker.radar2/admin/radar2.png radar2.png image/png
upload [11] radar2.admin /opt/iobroker/node_modules/iobroker.radar2/admin/index_m.html index_m.html text/html
upload [10] radar2.admin /opt/iobroker/node_modules/iobroker.radar2/admin/index.html index.html text/html
upload [9] radar2.admin /opt/iobroker/node_modules/iobroker.radar2/admin/i18n/zh-cn/translations.json i18n/zh-cn/translations.json application/json
upload [8] radar2.admin /opt/iobroker/node_modules/iobroker.radar2/admin/i18n/ru/translations.json i18n/ru/translations.json application/json
upload [7] radar2.admin /opt/iobroker/node_modules/iobroker.radar2/admin/i18n/pt/translations.json i18n/pt/translations.json application/json
upload [6] radar2.admin /opt/iobroker/node_modules/iobroker.radar2/admin/i18n/pl/translations.json i18n/pl/translations.json application/json
upload [5] radar2.admin /opt/iobroker/node_modules/iobroker.radar2/admin/i18n/nl/translations.json i18n/nl/translations.json application/json
upload [4] radar2.admin /opt/iobroker/node_modules/iobroker.radar2/admin/i18n/it/translations.json i18n/it/translations.json application/json
upload [3] radar2.admin /opt/iobroker/node_modules/iobroker.radar2/admin/i18n/fr/translations.json i18n/fr/translations.json application/json
upload [2] radar2.admin /opt/iobroker/node_modules/iobroker.radar2/admin/i18n/es/translations.json i18n/es/translations.json application/json
upload [1] radar2.admin /opt/iobroker/node_modules/iobroker.radar2/admin/i18n/en/translations.json i18n/en/translations.json application/json
upload [0] radar2.admin /opt/iobroker/node_modules/iobroker.radar2/admin/i18n/de/translations.json i18n/de/translations.json application/json
Adapter "radar2" updated

**Comment by Diginix** [comment]
The version number in io-package.json (line 4) was not updated to 1.2.3.

**Comment by frankjoke** [comment]
Ok, I updated both to 1.2.4 now! I forgot that I need to change multiple things to update a version number with ioBroker...

**Comment by Diginix** [comment]
Now the io-package.json is invald in line 61. The comma on line end is too much.
