### ISSUE TITLE
Error when radar2 v1.2.4 starts

### ISSUE THREAD

**Issue by Voodoo2man** [frankjoke/ioBroker.radar2#49]
I get a ton of errors whren radar2 1.2.4 starts.

![1C264C3A-88E7-4941-B839-084B5675C96E](https://user-images.githubusercontent.com/62031459/80955058-d8feac80-8dfe-11ea-95e0-9fb194020c7e.jpeg)

**Comment by Diginix** [comment]
I was unable to install 1.2.4 becaus of:
the io-package.json is invald in line 61. The comma on line end is too much.

`ertig mit Fehler: internal/modules/cjs/loader.js:800 throw err; ^SyntaxError: /opt/iobroker/node_modules/iobroker.radar2/io-package.json: Unexpected token } in JSON at position 4443 at JSON.parse () at Object.Module._extensions..json (internal/modules/cjs/loader.js:797:27) at Module.load (internal/modules/cjs/loader.js:653:32) at tryModuleLoad (internal/modules/cjs/loader.js:593:12) at Function.Module._load (internal/modules/cjs/loader.js:585:3) at Module.require (internal/modules/cjs/loader.js:692:17) at require (internal/modules/cjs/helpers.js:25:18) at Upload.uploadAdapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupUpload.js:481:19) at that.npmInstallWithCheck (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupInstall.js:1783:24) at ChildProcess.child.on.code (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupInstall.js:478:47)`

**Comment by frankjoke** [comment]
Ok, I corrected the io-package Problem on Git, same version and cannor reproduce Voodoo2man's Problem, which system and node/js-controller versions you are on?

**Comment by Voodoo2man** [comment]
Node.js 12.16.3
Js controller 3.0.20
I come from 1.2.0 and iobroker shows new update (still 1.2.3 available).
I updated manually to 1.2.4 and got the error messages in iobroker log.

**Comment by Voodoo2man** [comment]
I unistalles radar2 completely and installed 1.2.3 over iobroker. Now its without error. I di not get 1.2.4 offered from iobroker

**Comment by Voodoo2man** [comment]
I deleted radar2 now completely and installes it over iobroker. Now it shows that I have version 1.2.0 installes and update to 1.2.3 is available. No sign of 1.2.4

**Comment by frankjoke** [comment]
It takes days until iobroker recognizes new versions! You need to install from git, In Adapter/git select from github and then enter/select radar2. Then you should receive now 1.2.5 even because of another change I made for users of older system.
The iobroker-list latest is updated only once per day at best!

**Comment by Voodoo2man** [comment]
Ok thx.
Everything fine now for me. No error anymore.
