### ISSUE TITLE
Bluetooth-Problem

### ISSUE THREAD

**Issue by ue30er** [frankjoke/ioBroker.radar2#5]
Wenn ich am iPhone das wlan ausschalte wird es nach voreingestellter Zeit als offline gewertet. Bluetooth ist aber eingeschaltet. 
In der alten Version (Radar1) hat l2ping das offenbar dann gefunden; wird das jetzt so nicht mehr unterstützt?

Ansonsten: nice Job der neue Adapter. 

PS: hier funktioniert arp-Scan; im alten hab ich es nicht mehr ans laufen gebracht trotz gleicher Befehlszeile...

**Comment by frankjoke** [comment]
Sorry, aber l2ping wird nicht mehr verwendet da es damit Probleme gab. Werd bei der nächsten Version mal drauf schauen ob ich es wieder hinkriege.

**Comment by thurbo** [comment]
Das wäre sehr schön.
Fuxt mich auch ein bisschen, bluetooth war immer beste option für mich
