### ISSUE TITLE
Please Help / Bitte um Hilfe (Neither noble nor hcitool available to scan Bluetooth)

### ISSUE THREAD

**Issue by sreevo** [frankjoke/ioBroker.radar2#51]
//English / Sorry for bad translation

Since I updated the iobroker from the JS controller, the Bluetooth from the Radar2 no longer works. the log knocks me out the WARNING ((1265) Neither noble nor hcitool available to scan Bluetooth!).
I already installed classy new ones, I think so, but it still doesn't work.

//German

Seitdem ich beim iobroker ein Update gemacht habe vom JS-controller, funktioniert das Bluetooth vom Radar2 nicht mehr. die Log haut mir das WARNING ( (1265) Neither noble nor hcitool available to scan Bluetooth!) raus.
Habe schon noble neu installiert, ich glaube auch richtig, trotzdem funktioniert es nicht.

**Comment by frankjoke** [comment]
@sreevo, at first please updare radar2 from git to get today's changes.
Then you need to make sure to have latest stable nodejs (12) because noble may not work  with older nodes.
hcitools might need to be installed manually (like on my buster server) and also it's path might need to be included in your .bashrc

**Comment by sreevo** [comment]
my node version is 12.16.3.

how can i update to a newer version?

**Comment by sreevo** [comment]
please help me.

**Comment by frankjoke** [comment]
Du kannst auch deutsch schreiben, ich schreib oft Englisch damit die anderen es auch lesen können (wenn du es lesen kannst).

Du brauchst keine neuere Version. Hast die letzte Version von radar2 vom git geladen und zugeschaut ob Fehler bei der Installation kommen (von npm oder so)? wenn ja dann kanns daran liegen dass du nicht die letzten Versionen der node-developmen-Geschichten (gyp...) geladen hast.
Starte den Adapter dann im debug-mode und schau auf den log was er meldet. 
Ohne irgendwelche Fehlermeldungen kjann ich nicht helfen!

**Comment by sreevo** [comment]
Hey Frank, danke erstmal für deine Hilfe.

radar2.0	2020-05-04 22:27:00.539	info	(4670) debug: radar2 found uIP's: []
radar2.0	2020-05-04 22:27:00.519	warn	(4670) Neither noble nor hcitool available to scan bluetooth!
radar2.0	2020-05-04 22:27:00.519	info	(4670) debug: Neither BT scan nor l2ping are available to scan normal BT devices!
radar2.0	2020-05-04 22:27:00.517	info	(4670) debug: Neither noble nor hcitool available!
radar2.0	2020-05-04 22:26:52.405	info	(4670) debug: radar2 found uBT's: []
radar2.0	2020-05-04 22:26:52.404	info	(4670) debug: and not here (StenHandy, StenBLE, MichelleBLE)
radar2.0	2020-05-04 22:26:52.403	info	(4670) debug: and who here (MichelleHandy)
radar2.0	2020-05-04 22:26:52.402	info	(4670) debug: radar2 found here (MichelleHandy)
radar2.0	2020-05-04 22:26:52.389	info	(4670) debug: ChangeState ack:true of MichelleHandy._lastHere = 2020-05-04@22:26:52
radar2.0	2020-05-04 22:26:52.374	info	(4670) debug: arp-scan -lgq --retry=5 --timeout=400 --interface=wlan0 executed for 6.827 seconds and returned 11 hosts.
radar2.0	2020-05-04 22:26:45.539	info	(4670) debug: radar2 found uIP's: []
radar2.0	2020-05-04 22:26:45.519	warn	(4670) Neither noble nor hcitool available to scan bluetooth!

**Comment by frankjoke** [comment]
Welches Betriebssystem hast und kannst z,B `hcitool devices` auf der Kommandozeile eingeben und erscheint dann ein Fehler?
Hast die Installationsbefehle vom readme ausgeführt (muss nach jedem update von nodej gemacht werden)?
Oben sehe ich nur dass radar2 weder noble noch hcitool findet! noble wird bei der Installation des Adapters mittels npm installiert und hcitool musst mit linux-bordmitteln installieren oder konfigurieren!

**Comment by sreevo** [comment]
Wenn ich hcitooldevice eingebe zeigt er mir denconboard bluetooth vom raspberry 4 und den eingesteckt en ubs bluetooth dongle an (hat vorher funktioniert über den USB dongle) hab auch auf hci0 gestellt im Radar damit er den USB dongle ansteuert. Habe rasbian auf dem raspberry installiert.

**Comment by frankjoke** [comment]
Ich habe auch einen Raspi4 für ein Testsystem mit buster und nodejs 12.
Hab's grad probiert und funktioniert.
Also kanns nur an deinem speziellen Install liegen.
Hast die npm logs schon angeschaut und das System auf den letzten Stand gebracht?

**Comment by sreevo** [comment]
Wie seh ich mir die logd an und wie bringe ich es auf den neusten Stand?

**Comment by frankjoke** [comment]
Wenn du den Adapter installierst und auf detaqils oder mehr gehst (und nicht automatich schliesst) dann erscheint der log am Bildschirm bzw win Hinweis wo er abgespeichert ist.
Das System-update mit `sudo apt-get update` und dann `sudo apt-get -y upgrade` und dann ein reboot...

**Comment by sreevo** [comment]
Hab das System update ausgeführt. Hab immernoch noch NPM 6.14.4 drauf. Ist das die neuste Version?

**Comment by frankjoke** [comment]
Das hab ich auch, aber npm ist nicht das Problem! Das Problem ist dass in iobroker weder noble noch hcitool gefunden wird! der Adapter benutzt das System und ioBroker um diese zu finden, also kann nur eines der zwei schuld sein!

**Comment by sreevo** [comment]
Und wie kann ich das rausfinden was nun schuld ist und wie bekomme ich es zum laufen?

**Comment by sreevo** [comment]
Ich hab auch die Desktop Version von Debian installiert. Vll hilft dir das weiter. Muss ich vielleicht irgend n Bluetooth ausstellen oder so weil was anderes nicht drauf zu greifen kann. Oder wenn du zeit hast willst du mal per Teamviewer auf den rasp?

**Comment by sreevo** [comment]
(3170) Noble not available, Error: Error: The module '/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/binding.node'was compiled against a different Node.js version usingNODE_M
radar2.0	2020-05-05 00:55:14.418	warn	(3170) node-bluetooth not found!

**Comment by sreevo** [comment]
ich hab nun einfach mal npm install noble reingehaun und es kommen mehrere warn und errors

make: *** [binding.target.mk:109: Release/obj.target/binding/src/BluetoothHciSocket.o] Fehler 1
make: Verzeichnis „/home/pi/node_modules/bluetooth-hci-socket/build“ wird verlassen
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.19.97-v7l+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/node_modules/bluetooth-hci-socket
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN saveError ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@~0.1.4 (node_modules/noble/node_modules/xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bluetooth-hci-socket@0.5.1 (node_modules/bluetooth-hci-socket):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bluetooth-hci-socket@0.5.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ noble@1.9.1
updated 1 package and audited 114 packages in 118.757s

1 package is looking for funding
  run `npm fund` for details

found 3 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

vll kannst du damit was anfangen? gruß

**Comment by sreevo** [comment]
das kommt jetzt bei der iobroker log


radar2.0 | 2020-05-05 07:07:42.162 | warn | (3429) Noble not available, Error: Error: The module '/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/binding.node'was compiled against a different Node.js version usingNODE_M
-- | -- | -- | --
radar2.0 | 2020-05-05 07:07:42.042 | warn | (3429) node-bluetooth not found!

**Comment by frankjoke** [comment]
@sreevo , Du benutzt git issues hier nicht richtig. 
Es ist dazu da Fehler im Adapter zu melden und nicht zu helfen Fehler im Systemsetup oder bei der Adapterinstallation zu klären.
Es gibt einen langenthread im Forum über/mit radar2.
Zu deinen letzten 2 postings: Wenn du npm install in deinem Homeverzeichnis machst dann wird der das in diesem Verzeichnis installiert, und nicht in iobroker! Dort kannst nur mit Admin/git/beliebig und dann z,b die git-Adresse4 des Adapters `https://github.com/frankjoke/ioBroker.radar2` eingibst.
Ausserdem hast du das falsche noble installiert, wie du im Adapter lesen könntest verwende ich `@abandonware/noble` da das original-noble seit 4 Jahren nicht mehr gewartet wird. Du hast im alten noble sogar einen issue eröffnet der von @abandonware/noble spricht!

dein letzter post hier saght mir dass du nodejs upgedated hast und den Adapter (und die scripts) dann nicht neu installiert hast da der Adapter alte Versionen von code findet! Das passiert z.B. wenn du von v10 auf v12 gehst.

Bitte deinstalliere den Adapter komplett (keine instanz mehr und adapter im admin log mut uninstall gelöscht, das macht Adamin..) und dann von git wieder installieren damit du keinen alten Schrott hast.
