### ISSUE TITLE
Radar2 Module not found v1.9.9

### ISSUE THREAD

**Issue by larskeller** [frankjoke/ioBroker.radar2#54]
ich habe gerade die neuste Radar2 Version installiert und nach dem Update startet die Instance nicht mehr.

`host.raspberrypi | 2020-05-31 23:48:20.421 | info | Restart adapter system.adapter.radar2.0 because enabled
-- | -- | -- | --
host.raspberrypi | 2020-05-31 23:48:20.421 | error | instance system.adapter.radar2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.raspberrypi | 2020-05-31 23:48:20.421 | error | Caught by controller[0]: }
host.raspberrypi | 2020-05-31 23:48:20.421 | error | Caught by controller[0]: ]
host.raspberrypi | 2020-05-31 23:48:20.420 | error | Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.radar2/radar2.js'
host.raspberrypi | 2020-05-31 23:48:20.420 | error | Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.radar2/myNetworks.js',
host.raspberrypi | 2020-05-31 23:48:20.420 | error | Caught by controller[0]: requireStack: [
host.raspberrypi | 2020-05-31 23:48:20.420 | error | Caught by controller[0]: code: 'MODULE_NOT_FOUND',
host.raspberrypi | 2020-05-31 23:48:20.420 | error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:1026:19) {
host.raspberrypi | 2020-05-31 23:48:20.419 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:879:14)
host.raspberrypi | 2020-05-31 23:48:20.419 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:986:32)
host.raspberrypi | 2020-05-31 23:48:20.419 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
host.raspberrypi | 2020-05-31 23:48:20.419 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:1138:30)
host.raspberrypi | 2020-05-31 23:48:20.419 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.radar2/myNetworks.js:19:13)
host.raspberrypi | 2020-05-31 23:48:20.419 | error | Caught by controller[0]: at require (internal/modules/cjs/helpers.js:72:18)
host.raspberrypi | 2020-05-31 23:48:20.418 | error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:1026:19)
host.raspberrypi | 2020-05-31 23:48:20.418 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:842:27)
host.raspberrypi | 2020-05-31 23:48:20.418 | error | Caught by controller[0]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
host.raspberrypi | 2020-05-31 23:48:20.418 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.radar2/radar2.js
host.raspberrypi | 2020-05-31 23:48:20.418 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.radar2/myNetworks.js
host.raspberrypi | 2020-05-31 23:48:20.417 | error | Caught by controller[0]: Require stack:
host.raspberrypi | 2020-05-31 23:48:20.417 | error | Caught by controller[0]: Error: Cannot find module './lib/vendors.json'
host.raspberrypi | 2020-05-31 23:48:20.417 | error | Caught by controller[0]: ^
host.raspberrypi | 2020-05-31 23:48:20.417 | error | Caught by controller[0]: throw err;
host.raspberrypi | 2020-05-31 23:48:20.416 | error | Caught by controller[0]: internal/modules/cjs/loader.js:969
host.raspberrypi | 2020-05-31 23:48:20.027 | info | instance system.adapter.radar2.0 started with pid 17332
host.raspberrypi | 2020-05-31 23:47:49.999 | info | Restart adapter system.adapter.radar2.0 because enabled`

**Comment by frankjoke** [comment]
Kannst jetzt nochmals probieren? habe gerade die newV2 mit master gemerged und du scheinst da grad mitten drinnen probiert zu haben.

**Comment by larskeller** [comment]
Klappt perfekt. Danke!
