### ISSUE TITLE
isHere aktualisiert sich erst nach weiterem scan

### ISSUE THREAD

**Issue by Speedbreaker12** [frankjoke/ioBroker.radar2#55]
Hi Frank,
ich hab ein kleines Problem mit mehreren scripten nachdem ich auf 2.0 aktualisiert habe.
Wie schon im Titel beschrieben, scheint es so zu sein, dass die Namensliste isHere, erst nach dem True der einzelnen _here elemente geupdated wird. Das war in den alten Versionen anders, darum wird, wenn man auf here triggert, eine leere Namenslisste ausgelesen.

**Comment by frankjoke** [comment]
@Speedbreaker12 , zuerst eine Bitte, würdest du solche Fragen im Forum stellen? z.B. auf https://forum.iobroker.net/topic/23010/iobroker-radar2 
isHere wurde immer erst am Ende des scans upgedated da zuerst alle Geräte durchgetestet werden müssen bevor die Liste generiert werden kann. _here hingegen wird sofort gesetzt, also wenn das Gerät entdeckt wird. Das kan 1 Sekunde nach Scan start sein oder 20 Sekunden danach, wenn ein 30s scan z.B. wirklich nur 28 Sekunden dauert dann werden aber erst nach den 28 Sekunden die Listen erzeugt da vorher nicht bekannt ist ob nicht noch wer erkannt wird. Das einzige was sich geändert hat ist dass ich nicht bei jedem update neu den Wert von _here (_nHere... und allen adneren) schreibe sondern NUR wenn sich einer dieser Werte ändern umd nicht hunderte Werte zu setzten die sich aber nicht verändert werden.
