### ISSUE TITLE
Cannot read property 'push' 

### ISSUE THREAD

**Issue by obodeldog** [frankjoke/ioBroker.radar2#56]
Hi. Folgender Fehler bei 2.0.1 kommt und startet daher nicht.
![image](https://user-images.githubusercontent.com/35403739/83750629-d98c9c00-a665-11ea-86bf-3767bafaeb73.png)

**Comment by frankjoke** [comment]
Bitte im Forum z.B. unter https://forum.iobroker.net/topic/23010/iobroker-radar2 weiterdiskutieren und keine git issues aufmachen bevor man sich dort nicht sicher ist dass es ein Fehler vom Adapter ist!
