### ISSUE TITLE
Adapter springt hin und her rot/Gelb

### ISSUE THREAD

**Issue by Schrader1** [frankjoke/ioBroker.radar2#57]
`Hallo 
Radar2 läuft auf Meinem Master Host ohne probleme, jedoch auf meinem Slave Host überhaupt nicht, siehe LOG.

Ich komme nicht weiter

radar2.2 | 2020-06-17 10:45:58.445 | warn | (751) Promise problem unhandledRejection of Promise Promise { <rejected> TypeError: A.C.knownBTs.toLowerCase is not a function at /opt/iobroker/node_modules/iobroker.radar2/radar2.js:464:41 at process
-- | -- | -- | --
radar2.2 | 2020-06-17 10:45:58.440 | info | (751) Adapter disconnected and stopped with dostop(false) and callback(true)
radar2.2 | 2020-06-17 10:45:58.436 | error | (751) TypeError: A.C.knownBTs.toLowerCase is not a function at /opt/iobroker/node_modules/iobroker.radar2/radar2.js:464:41 at processTicksAndRejections (internal/process/task_queues.js:97:5)
radar2.2 | 2020-06-17 10:45:58.433 | error | (751) unhandled promise rejection: A.C.knownBTs.toLowerCase is not a function
radar2.2 | 2020-06-17 10:45:58.431 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
radar2.2 | 2020-06-17 10:45:58.425 | info | (751) radar2 set to flag items away if they are not seen for 3 minutes
radar2.2 | 2020-06-17 10:45:58.424 | warn | (751) node-bluetooth not found!
radar2.2 | 2020-06-17 10:45:58.420 | warn | (751) Noble not available, Error: Error: The module '/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/binding.node'was compiled against a different Node.js version usingNODE_MO
radar2.2 | 2020-06-17 10:45:57.759 | info | (751) Connected with '0.0.0.0' for DHCP Scan
radar2.2 | 2020-06-17 10:45:57.275 | info | (751) net-ping not available! Will try to use normal ping!
radar2.2 | 2020-06-17 10:45:57.232 | info | (751) radar2 initialization started...
radar2.2 | 2020-06-17 10:45:57.182 | warn | (751) adapter.objects.getObjectList is deprecated, and will be removed in the future. Please use adapter.getObjectList/Async. Report this to Developer!
radar2.2 | 2020-06-17 10:45:56.997 | info | (751) starting. Version 1.0.9 in /opt/iobroker/node_modules/iobroker.radar2, node: v14.4.0, js-controller: 3.1.5

`

**Comment by frankjoke** [comment]
Die Version die du verwendest ist sehr alt und für deine neuen nodejs und js-controller nicht vorbereitet. Kannst bitte letzte Version von latest oder git verwenden (V2.0.1)?

Und, bitte im Forum, z.B unter https://forum.iobroker.net/topic/23010/iobroker-radar2 solche Frangen stellen und nicht einen git issue öffnen bevor du nicht sicher bist ob es ein reproduzierbarer bug ist.
