### ISSUE TITLE
iobroker nach radar2 sehr langsam

### ISSUE THREAD

**Issue by sreevo** [frankjoke/ioBroker.radar2#59]
hallo frank, ich habe aufeinmal 16000 objecte im iobroker und er ist sehr langsam. glaube der sucht die ganze zeit die Bluetooth geräte. wie kann ich es einstellen dass er nur die bluetoothgeräte sucht die ich eingegeben habe? im uBTs Ordner sind soviele Objecte dass dass es ewig dauert den Ordner überhaupt zu öffnen.

mfg

**Comment by frankjoke** [comment]
In der letzten Version (auf latest) kannst ausschalten  dass für jedes gefundene BT-Gerät ein Objekt kreiert wird!
