### ISSUE TITLE
Warn:  Cannot read property 'pE' of undefinedat pE 

### ISSUE THREAD

**Issue by Haba1234** [frankjoke/ioBroker.radar2#6]
Hi!

In the log writes:
...
radar initialization finished with error TypeError: Cannot read property 'pE' of undefinedat pE (/opt/iobroker/node_modules/@frankjoke/myadapter/myAdapter.js:387:26)at <anonymous>at process._tickCallb
Adapter disconnected and stopped with dostop(1) and callback(false)
instance system.adapter.radar2.0 terminated with code 0 (OK)
Restart adapter system.adapter.radar2.0 because enabled
...
and then reboots.

And the arp-scan command does not work in the driver. Running a command from the command line works

**Comment by frankjoke** [comment]
Can you check latest git version?
