### ISSUE TITLE
Wenn die Installation im LXC-Container nicht klappt... Proxmox

### ISSUE THREAD

**Issue by AlexanderSch90** [frankjoke/ioBroker.radar2#7]
Eine kurze Info für alle welche Proxmox in einem unprivilegierten LXC Container laufen haben:

Dadurch, dass dieser unprivilegiert ist hat er kein Recht auf den arp-scan. Entsprechen wird der Adapter immer grün und rot im wechsel. 

Folgende Fehlermeldung kam bei mir im Log:

```
host.Debian-iobroker | 2019-04-02 21:23:45.084 | info | Restart adapter system.adapter.radar2.0 because enabled
-- | -- | -- | --
host.Debian-iobroker | 2019-04-02 21:23:45.084 | error | instance system.adapter.radar2.0 terminated with code null ()
host.Debian-iobroker | 2019-04-02 21:23:45.084 | warn | instance system.adapter.radar2.0 terminated due to SIGABRT
Caught | 2019-04-02 21:23:45.083 | error | by controller[0]: .0: ../deps/uv/src/unix/poll.c:123: uv_poll_start: Assertion `!(((handle)->flags & (UV_HANDLE_CLOSING \| UV_HANDLE_CLOSED)) != 0)' failed.
radar2.0 | 2019-04-02 21:23:44.714 | info | radar2 initialization started...
radar2.0 | 2019-04-02 21:23:42.644 | info | starting. Version 1.0.5 in /opt/iobroker/node_modules/iobroker.radar2, node: v8.15.1
radar2.0 | 2019-04-02 21:23:42.628 | info | States connected to redis: 0.0.0.0:6379
host.Debian-iobroker | 2019-04-02 21:23:42.195 | info | instance system.adapter.radar2.0 started with pid 1471

```

Ich denke dies hilft anderen... Die User mit iobroker auf Proxmox im Container werden immer mehr...

**Comment by timae146** [comment]
ich hab mich tot gesucht bevor ich das issue hier gefunden habe.. vllt. wäre es sinnvoll einen hinweiß für diesen fall in die adapterbeschreibung zu packen?

gibts hierzu schon einen eleganteren workaround?

ich habe momentan eine extra debian vm laufen mit einem iobroker multihost, da ich nicht unbedingt  mit meinem ganzen system "umziehen" will.

**Comment by robbsta** [comment]
Moin, ich bin auch in diesen Fehler, in Verbindung mit Proxmox gelaufen.
Folgende Zeile verursacht den Fehler (genauer: noble.on('stateChange',...))
https://github.com/frankjoke/ioBroker.radar2/blob/803647663fcb25a5f89041ca1b813f0069f0998b/myNetworks.js#L407

Ob der Container privilegiert oder unprivilegiert war, hat bei mir keinen Unterschiede gemacht.
Auch ein konkretes Mappen der USB-Verbindung brachte keine Änderung.

In Version 1.2 konnte ich als Workaround auf hcitool umzustellen, dann läuft der Adapter wieder wie erwartet.
