### ISSUE TITLE
Gerät nicht zählen

### ISSUE THREAD

**Issue by AlexanderSch90** [frankjoke/ioBroker.radar2#8]
Hallo,

mega Adapter!

Eine Frage: If you put a - at the end of a name the device will not be counted in the _notHere or _isHere.

Das funktioniert bei mir nicht. Muss das "-" direkt an den Namen oder mit Leerzeile? Wo genau muss das hin?

Danke dir!

**Comment by frankjoke** [comment]
Wenn man ein - direkt nach dem Namen setzt (so wie `HandyTochter-`, der Gerätenamen im Baum bleibt dann `HandyTochter`) dann wird das Gerät nicht in _isHere gelistet und in _nHere gezählt.
Es bleibt in _allHere drinnen wenn da und in _notHere wenn nicht da.

p.s: Nicht solche Fragen als Issue öffnen sondern im Forum stellen!
https://forum.iobroker.net/topic/19794/adapter-neuer-radar2-adapter

Issues sind da um Programmfehler zu melden die definitiv keine Konfigurations oder Eingabefehler sind!

**Comment by AlexanderSch90** [comment]
Okay, dass heißt ich bekomme es so nicht aus dem Bereich _notHere und _nHere raus?!
Dies wäre jedoch genau das was ich suche. 
Wäre es ggf. möglich den Adapter zu erweitern, dass man die "ignorierten Geräte" wirklich ignoriert. 
Ich benötige für die ignorierten Geräte nur den Einzelstatus jedoch möchte ich diese nicht in den Summen haben... 

![2019-04-07_15-24-45](https://user-images.githubusercontent.com/37745917/55684247-5a101980-5949-11e9-82ee-b45be3cfd304.jpg)
![2019-04-07_15-22-26](https://user-images.githubusercontent.com/37745917/55684250-64321800-5949-11e9-92b5-f5ac60c50da9.jpg)

**Comment by frankjoke** [comment]
in _nHere sind sie nicht drinnern, nur in _allHere!
